name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Fix file ownership
        run: sudo chown -R $(whoami):$(whoami) /home/ec2-user/actions-runner/_work/sort-my-college-app-backend

      - name: Set correct permissions
        run: sudo chmod -R u+rwx /home/ec2-user/actions-runner/_work/sort-my-college-app-backend

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          clean: true
          persist-credentials: false

      # Install PM2 (if not installed)
      - name: Install PM2
        run: sudo npm install pm2 -g

      # Install project dependencies
      - name: Install dependencies
        run: |
          npm ci --prefix counselor
          npm ci --prefix admin
          npm ci --prefix notification-service
          npm ci --prefix user
          npm ci --prefix entrance-preparation
          npm ci --prefix api-gateway

      # Create environment variables for each service
      - name: Create environment variables
        run: |
          echo "${{ secrets.COUNSELLOR_SECRETS }}" > counselor/.env
          echo "${{ secrets.ADMIN_SECRETS }}" > admin/.env
          echo "${{ secrets.NOTIFICATION_SERVICE_SECRETS }}" > notification-service/.env
          echo "${{ secrets.USER_SECRETS }}" > user/.env
          echo "${{ secrets.EP_SECRETS }}" > entrance-preparation/.env
          echo "${{ secrets.API_GATEWAY_SECRETS }}" > api-gateway/.env
          echo "${{ secrets.FIREBASE_SERVICE_KEY }}" | base64 --decode > notification-service/firebaseServiceKey.json

      # Start or Reload Node.js applications using PM2 (Zero Downtime)
      - name: Start or Reload Node.js applications
        run: |
          # Start services if not already running, otherwise reload them
          for service in counselor admin notification-service user entrance-preparation api-gateway; do
            cd $service
            if pm2 list | grep -q $service; then
              sudo pm2 reload $service --update-env
            else
              sudo pm2 start server.js --name="$service" -f
            fi
            cd ..
          done
