name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Log in as root
        run: sudo su
      - name: Install PM2
        run: npm install -g pm2
      - name: Verify PM2 Installation
        run: pm2 --version
      # - name: Stop all instances of pm2
      #   run: pm2 stop all || true
      - name: Stop all instances of pm2
        run: /root/.nvm/versions/node/v20.8.0/bin/pm2 stop all || true
      - name: Install dependencies
        run: |
          cd counselor
          npm ci

          cd ../admin
          npm ci

          cd ../notification-service
          npm ci

          cd ../user
          npm ci

          cd ../api-gateway
          npm ci

          cd ../entrance-preparation
          npm ci

      - name: Create SSL certificates
        run: |
          cd ssl_certificates
          touch ca_bundle.crt
          echo "${{ secrets.CA_BUNDLE }}" > ca_bundle.crt
          touch certificate.crt
          echo "${{ secrets.CERTIFICATE }}" > certificate.crt
          touch private.key
          echo "${{ secrets.PRIVATE_KEY }}" > private.key

      - name: Create environment variables
        run: |
          cd counselor
          touch .env
          echo "${{ secrets.COUNSELLOR_SECRETS }}" > .env
          cd ../admin
          touch .env
          echo "${{ secrets.ADMIN_SECRETS }}" > .env
          cd ../notification-service
          touch .env
          echo "${{ secrets.NOTIFICATION_SERVICE_SECRETS }}" > .env
          cd ../user
          touch .env
          echo "${{ secrets.USER_SECRETS }}" > .env
          cd ../entrance-preparation
          touch .env
          echo "${{ secrets.EP_SECRETS }}" > .env
          cd ../api-gateway
          touch .env
          echo "${{ secrets.API_GATEWAY_SECRETS }}" > .env

      - name: Start Node.js applications
        run: |
          cd counselor
          /root/.nvm/versions/node/v20.8.0/bin/pm2 start server.js --name="counsellor" -f

          cd ../admin
          /root/.nvm/versions/node/v20.8.0/bin/pm2 start server.js --name="admin" -f

          cd ../notification-service
          /root/.nvm/versions/node/v20.8.0/bin/pm2 start server.js --name="notification-service" -f

          cd ../user
          /root/.nvm/versions/node/v20.8.0/bin/pm2 start server.js --name="user" -f

          cd ../entrance-preparation
          /root/.nvm/versions/node/v20.8.0/bin/pm2 start server.js --name="entrance-preparation" -f

          cd ../api-gateway
          /root/.nvm/versions/node/v20.8.0/bin/pm2 start server.js --name="api-gateway" -f

      - name: Restart all Node.js applications
        run: /root/.nvm/versions/node/v20.8.0/bin/pm2 restart all
