name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # Install PM2
      - name: Install PM2
        run: npm install pm2 -g

      # Stop all instances of PM2
      - name: Stop all instances of PM2
        run: sudo pm2 delete all || true

      # Install project dependencies
      - name: Install dependencies
        run: |
          npm ci --prefix counselor
          npm ci --prefix admin
          npm ci --prefix notification-service
          npm ci --prefix user
          npm ci --prefix entrance-preparation
          npm ci --prefix api-gateway

      # Create SSL certificates
      # - name: Create SSL certificates
      #   run: |
      #     sudo mkdir -p ssl_certificates
      #     sudo touch ssl_certificates/ca_bundle.crt
      #     echo "${{ secrets.CA_BUNDLE }}" | sudo tee ssl_certificates/ca_bundle.crt
      #     sudo touch ssl_certificates/certificate.crt
      #     echo "${{ secrets.CERTIFICATE }}" | sudo tee ssl_certificates/certificate.crt
      #     sudo touch ssl_certificates/private.key
      #     echo "${{ secrets.PRIVATE_KEY }}" | sudo tee ssl_certificates/private.key

      # Create environment variables for each service
      - name: Create environment variables
        run: |
          echo "${{ secrets.COUNSELLOR_SECRETS }}" > counselor/.env
          echo "${{ secrets.ADMIN_SECRETS }}" > admin/.env
          echo "${{ secrets.NOTIFICATION_SERVICE_SECRETS }}" > notification-service/.env
          echo "${{ secrets.USER_SECRETS }}" > user/.env
          echo "${{ secrets.EP_SECRETS }}" > entrance-preparation/.env
          echo "${{ secrets.API_GATEWAY_SECRETS }}" > api-gateway/.env

      # Start Node.js applications using PM2
      - name: Start Node.js applications
        run: |
          # Change directory to each service and start the server with PM2
          cd counselor
          sudo pm2 start server.js --name="counsellor" -f

          cd ../admin
          sudo pm2 start server.js --name="admin" -f

          cd ../notification-service
          sudo pm2 start server.js --name="notification-service" -f

          cd ../user
          sudo pm2 start server.js --name="user" -f

          cd ../entrance-preparation
          sudo pm2 start server.js --name="entrance-preparation" -f

          cd ../api-gateway
          sudo pm2 start server.js --name="api-gateway" -f

      - name: Restart all Node.js applications
        run: sudo pm2 restart all
