name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # Install PM2
      - name: Install PM2
        run: npm install pm2 -g

      # Stop all instances of PM2
      - name: Stop all instances of PM2
        run: pm2 stop all || true

      # Install project dependencies for each service
      - name: Install dependencies
        run: |
          npm ci --prefix counselor
          npm ci --prefix admin
          npm ci --prefix notification-service
          npm ci --prefix user
          npm ci --prefix entrance-preparation
          npm ci --prefix api-gateway

      # Create SSL certificates
      - name: Create SSL certificates
        run: |
          touch ssl_certificates/ca_bundle.crt
          echo "${{ secrets.CA_BUNDLE }}" > ssl_certificates/ca_bundle.crt
          touch ssl_certificates/certificate.crt
          echo "${{ secrets.CERTIFICATE }}" > ssl_certificates/certificate.crt
          touch ssl_certificates/private.key
          echo "${{ secrets.PRIVATE_KEY }}" > ssl_certificates/private.key

      # Create environment variables for each service
      - name: Create environment variables
        run: |
          echo "${{ secrets.COUNSELLOR_SECRETS }}" > counselor/.env
          echo "${{ secrets.ADMIN_SECRETS }}" > admin/.env
          echo "${{ secrets.NOTIFICATION_SERVICE_SECRETS }}" > notification-service/.env
          echo "${{ secrets.USER_SECRETS }}" > user/.env
          echo "${{ secrets.EP_SECRETS }}" > entrance-preparation/.env
          echo "${{ secrets.API_GATEWAY_SECRETS }}" > api-gateway/.env

      # Start Node.js applications using PM2
      - name: Start Node.js applications
        run: |
          # Change directory to each service and start the server with PM2
          cd counselor && pm2 start server.js --name="counsellor" -f
          cd admin && pm2 start server.js --name="admin" -f
          cd notification-service && pm2 start server.js --name="notification-service" -f
          cd user && pm2 start server.js --name="user" -f
          cd entrance-preparation && pm2 start server.js --name="entrance-preparation" -f
          cd api-gateway && pm2 start server.js --name="api-gateway" -f

      # Restart all Node.js applications managed by PM2
      - name: Restart all Node.js applications
        run: pm2 restart all
